spring.application.name=back-end

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/java_capstone

spring.datasource.username=root

spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-message=always

spring.web.error.include-stacktrace=always

spring.data.mongodb.uri=mongodb://localhost:27017

management.endpoint.health.show-details=always
management.health.db.enabled=true


api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M



spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8